// Generated by scripts/collect-release-notes.ts. Do not edit by hand.

import type { ReleaseNote, ReleaseNoteEntry } from "@colibri-social/lib";
import type { ReleaseNoteIcon } from "./icons";

export type ClientReleaseNote = Omit<ReleaseNote, "entries"> & {
	entries: Array<Omit<ReleaseNoteEntry, "icon"> & { icon: ReleaseNoteIcon }>;
};

export const RELEASE_NOTES: Array<ClientReleaseNote> = [];
