// Generated by scripts/collect-release-notes.ts. Do not edit by hand.

import type { ReleaseNote, ReleaseNoteEntry } from "@colibri-social/lib";
import type { ReleaseNoteIcon } from "./icons";

export type ClientReleaseNote = Omit<ReleaseNote, "entries"> & {
	entries: Array<Omit<ReleaseNoteEntry, "icon"> & { icon: ReleaseNoteIcon }>;
};

export const RELEASE_NOTES: Array<ClientReleaseNote> = [
	{
		version: "0.1.0-rc.14",
		date: "2026-08-02",
		entries: [
			{
				title: "A hummingbird while you wait",
				body: "Loading screens now show a hovering hummingbird instead of plain text, with status lines that keep you company while the app starts up. Tap it if you want to see it startle.",
				icon: "bird-fill",
				kind: "feature",
			},
			{
				title: "Better errors",
				body: "When something goes wrong you now get a clear reason and a way to retry!",
				icon: "warning-circle-fill",
				kind: "feature",
			},
			{
				title: "A window title bar of our own",
				body: "The desktop app now has the same branded header as the web app, with the channel you're in shown in the title bar and the taskbar.",
				icon: "browser-fill",
				kind: "feature",
			},
			{
				title: "A new way to sign in",
				body: "Our sign-in screen got reworked! Check if out when you have a chance.",
				icon: "sign-in-fill",
				kind: "feature",
			},
			{
				title: "Open sign-in",
				body: "Sign-in is now open to everyone, no more waitlist.",
				icon: "chat-circle-dots-fill",
				kind: "feature",
			},
			{
				title: "Screenshare and camera sounds for everyone",
				body: "Other people in a voice channel now hear a sound when you start screen sharing or turn your camera on or off.",
				icon: "speaker-high-fill",
				kind: "fix",
			},
			{
				title: "Accurate voice channel member lists",
				body: "Voice channels now show exactly who is in them, and keep it accurate through connection drops.",
				icon: "users-three-fill",
				kind: "fix",
			},
			{
				title: "Faster, fresher messages",
				body: "Channels now load up-to-date messages much sooner, and no longer show conversations that have fallen behind.",
				icon: "rewind-fill",
				kind: "fix",
			},
			{
				title: "MacOS voice channel issues",
				body: "MacOS users rejoice! You can finally join voice channels again.",
				icon: "speaker-high-fill",
				kind: "fix",
			},
			{
				title: "More reliable voice calls",
				body: "Fixed a bug where activity elsewhere (like opening another device) could silently break your voice call without disconnecting you.",
				icon: "speaker-high-fill",
				kind: "fix",
			},
			{
				title: "Editing formatted lists",
				body: "Editing a message that contains a bold or italic list item no longer scrambles the formatting.",
				icon: "list-bullets-fill",
				kind: "fix",
			},
		],
	},
	{
		version: "0.1.0-rc.11",
		date: "2026-07-29",
		entries: [
			{
				title: "Community banners",
				body: "Set a community banner to be displayed in the channel sidebar.",
				icon: "image-fill",
				kind: "feature",
			},
			{
				title: "Debug Information",
				body: 'The "About" page in the settings now contains debug information that can easily be copied.',
				icon: "bug-fill",
				kind: "feature",
			},
			{
				title: "What's New popup",
				body: "This popup you're seeing!",
				icon: "sparkle-fill",
				kind: "feature",
			},
			{
				title: "Improved Drag/Drop Handling",
				body: "Issues with dragging and dropping channels on Desktop should be resolved now.",
				icon: "hand-grabbing-fill",
				kind: "fix",
			},
			{
				title: "Live Banner Updates",
				body: "Updates made to a community's banner are now shown right away.",
				icon: "image-fill",
				kind: "fix",
			},
			{
				title: "Back Behavior",
				body: 'Using your mobile device\'s "navigate back" action should behave more predictably.',
				icon: "rewind-fill",
				kind: "fix",
			},
			{
				title: "Keyboard pinning",
				body: "The channel should now stay pinned to the bottom after sending a message.",
				icon: "keyboard-fill",
				kind: "fix",
			},
			{
				title: "Blockquotes",
				body: "Improves the way blockquotes are handled in the chat input",
				icon: "quotes-fill",
				kind: "fix",
			},
		],
	},
	{
		version: "0.1.0-rc.10",
		date: "2026-07-28",
		entries: [
			{
				title: "Community banners",
				body: "Set a community banner to be displayed in the channel sidebar.",
				icon: "image-fill",
				kind: "feature",
			},
			{
				title: "Debug Information",
				body: 'The "About" page in the settings now contains debug information that can easily be copied.',
				icon: "bug-fill",
				kind: "feature",
			},
			{
				title: "What's New popup",
				body: "This popup you're seeing!",
				icon: "sparkle-fill",
				kind: "feature",
			},
			{
				title: "Improved Drag/Drop Handling",
				body: "Issues with dragging and dropping channels on Desktop should be resolved now.",
				icon: "hand-grabbing-fill",
				kind: "fix",
			},
			{
				title: "Back Behavior",
				body: 'Using your mobile device\'s "navigate back" action should behave more predictably.',
				icon: "rewind-fill",
				kind: "fix",
			},
			{
				title: "Keyboard pinning",
				body: "The channel should now stay pinned to the bottom after sending a message.",
				icon: "keyboard-fill",
				kind: "fix",
			},
			{
				title: "Blockquotes",
				body: "Improves the way blockquotes are handled in the chat input",
				icon: "quotes-fill",
				kind: "fix",
			},
		],
	},
];
