// Generated by scripts/collect-release-notes.ts. Do not edit by hand.

import SparkleFillIcon from "~icons/ph/sparkle-fill";

export const RELEASE_NOTE_ICONS = {
	"sparkle-fill": SparkleFillIcon,
} as const;

export type ReleaseNoteIcon = keyof typeof RELEASE_NOTE_ICONS;

export const FALLBACK_RELEASE_NOTE_ICON =
	"sparkle-fill" satisfies ReleaseNoteIcon;
