// Generated by scripts/collect-release-notes.ts. Do not edit by hand.

import ArrowLineUpFillIcon from "~icons/ph/arrow-line-up-fill";
import BellRingingFillIcon from "~icons/ph/bell-ringing-fill";
import BirdFillIcon from "~icons/ph/bird-fill";
import BrowserFillIcon from "~icons/ph/browser-fill";
import BugFillIcon from "~icons/ph/bug-fill";
import ChatCircleDotsFillIcon from "~icons/ph/chat-circle-dots-fill";
import HandGrabbingFillIcon from "~icons/ph/hand-grabbing-fill";
import ImageFillIcon from "~icons/ph/image-fill";
import KeyboardFillIcon from "~icons/ph/keyboard-fill";
import LightningFillIcon from "~icons/ph/lightning-fill";
import ListBulletsFillIcon from "~icons/ph/list-bullets-fill";
import MonitorPlayFillIcon from "~icons/ph/monitor-play-fill";
import QuotesFillIcon from "~icons/ph/quotes-fill";
import RewindFillIcon from "~icons/ph/rewind-fill";
import SignInFillIcon from "~icons/ph/sign-in-fill";
import SparkleFillIcon from "~icons/ph/sparkle-fill";
import SpeakerHighFillIcon from "~icons/ph/speaker-high-fill";
import TrashFillIcon from "~icons/ph/trash-fill";
import UsersThreeFillIcon from "~icons/ph/users-three-fill";
import WarningCircleFillIcon from "~icons/ph/warning-circle-fill";

export const RELEASE_NOTE_ICONS = {
	"arrow-line-up-fill": ArrowLineUpFillIcon,
	"bell-ringing-fill": BellRingingFillIcon,
	"bird-fill": BirdFillIcon,
	"browser-fill": BrowserFillIcon,
	"bug-fill": BugFillIcon,
	"chat-circle-dots-fill": ChatCircleDotsFillIcon,
	"hand-grabbing-fill": HandGrabbingFillIcon,
	"image-fill": ImageFillIcon,
	"keyboard-fill": KeyboardFillIcon,
	"lightning-fill": LightningFillIcon,
	"list-bullets-fill": ListBulletsFillIcon,
	"monitor-play-fill": MonitorPlayFillIcon,
	"quotes-fill": QuotesFillIcon,
	"rewind-fill": RewindFillIcon,
	"sign-in-fill": SignInFillIcon,
	"sparkle-fill": SparkleFillIcon,
	"speaker-high-fill": SpeakerHighFillIcon,
	"trash-fill": TrashFillIcon,
	"users-three-fill": UsersThreeFillIcon,
	"warning-circle-fill": WarningCircleFillIcon,
} as const;

export type ReleaseNoteIcon = keyof typeof RELEASE_NOTE_ICONS;

export const FALLBACK_RELEASE_NOTE_ICON =
	"sparkle-fill" satisfies ReleaseNoteIcon;
