services:
  app:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
      args:
        - INVITE_API_KEY=${INVITE_API_KEY}
        - APPVIEW_DOMAIN=${APPVIEW_DOMAIN}
        - SAME_TLD_DID=${SAME_TLD_DID}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - SENTRY_DSN=${SENTRY_DSN}
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
        - SENTRY_RELEASE=${SENTRY_RELEASE}
        - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
        - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
        - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
    container_name: colibri-app
    restart: unless-stopped
    environment:
      - INVITE_API_KEY=${INVITE_API_KEY}
      - APPVIEW_DOMAIN=${APPVIEW_DOMAIN}
      - SAME_TLD_DID=${SAME_TLD_DID}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
    networks:
      - default

networks:
  default:
    enable_ipv6: true
