services:
  app:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
      args:
        - INVITE_API_KEY=${INVITE_API_KEY}
        - APPVIEW_DOMAIN=${APPVIEW_DOMAIN}
        - SAME_TLD_DID=${SAME_TLD_DID}
        - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
        - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
        - LIVEKIT_SERVER_URL=${LIVEKIT_SERVER_URL}
        - SENTRY_DSN=${SENTRY_DSN}
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    container_name: colibri-app
    restart: unless-stopped
    environment:
      - INVITE_API_KEY=${INVITE_API_KEY}
      - APPVIEW_DOMAIN=${APPVIEW_DOMAIN}
      - SAME_TLD_DID=${SAME_TLD_DID}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_SERVER_URL=${LIVEKIT_SERVER_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
