import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type {
	ReleaseNote,
	ReleaseNoteEntry,
} from "../packages/lib/src/release-notes.ts";
import { kindForBump } from "../packages/lib/src/release-notes.ts";
import {
	CHANGESET_DIR,
	clientBump,
	listChangesetFiles,
	readChangeset,
} from "./lib/changesets.ts";
import { iconProblem } from "./lib/icons.ts";

const KEEP_RELEASES = 5;
const FALLBACK_ICON = "sparkle-fill";
const PREVIEW_VERSION = "0.0.0-preview";

const STAGING_FILE = new URL(".whats-new-staged.json", CHANGESET_DIR);
const CLIENT_PACKAGE_JSON = new URL(
	"../packages/client/package.json",
	import.meta.url,
);
const DATA_FILE = new URL(
	"../packages/client/src/release-notes/data.ts",
	import.meta.url,
);
const ICONS_FILE = new URL(
	"../packages/client/src/release-notes/icons.ts",
	import.meta.url,
);

const GENERATED_HEADER =
	"// Generated by scripts/collect-release-notes.ts. Do not edit by hand.";

const writeGenerated = async (target: URL, contents: string) => {
	await mkdir(new URL(".", target), { recursive: true });
	await writeFile(target, contents);
};

interface Staged {
	entries: Array<ReleaseNoteEntry>;
	releaseTitle?: string;
	heroImage?: string;
}

const fail = (message: string): never => {
	console.error(`error: ${message}`);
	process.exit(1);
};

const gather = async (): Promise<Staged | undefined> => {
	const files = await listChangesetFiles();

	const collected: Array<{ entry: ReleaseNoteEntry; rank: number }> = [];
	let releaseTitle: string | undefined;
	let releaseTitleFrom: string | undefined;
	let heroImage: string | undefined;
	let heroImageFrom: string | undefined;

	for (const file of files) {
		let parsed: Awaited<ReturnType<typeof readChangeset>>;
		try {
			parsed = await readChangeset(file);
		} catch (error) {
			return fail(
				`.changeset/${file}: ${error instanceof Error ? error.message : String(error)}`,
			);
		}

		const block = parsed.block;
		if (!block) continue;

		const bump = clientBump(parsed);
		if (!bump) continue;

		const problem = iconProblem(block.icon);
		if (problem) return fail(`.changeset/${file}: ${problem}`);

		if (block.releaseTitle) {
			if (releaseTitle && releaseTitleFrom !== file) {
				return fail(
					`releaseTitle is set by both .changeset/${releaseTitleFrom} and .changeset/${file}, pick one`,
				);
			}
			releaseTitle = block.releaseTitle;
			releaseTitleFrom = file;
		}

		if (block.heroImage) {
			if (heroImage && heroImageFrom !== file) {
				return fail(
					`heroImage is set by both .changeset/${heroImageFrom} and .changeset/${file}, pick one`,
				);
			}
			heroImage = block.heroImage;
			heroImageFrom = file;
		}

		const kind = block.kind ?? kindForBump(bump);

		collected.push({
			entry: { title: block.title, body: block.body, icon: block.icon, kind },
			rank: kind === "fix" ? 1 : 0,
		});
	}

	const entries = collected
		.map((item, index) => ({ ...item, index }))
		.sort((a, b) => a.rank - b.rank || a.index - b.index)
		.map((item) => item.entry);

	if (entries.length === 0) return undefined;

	const staged: Staged = { entries };
	if (releaseTitle) staged.releaseTitle = releaseTitle;
	if (heroImage) staged.heroImage = heroImage;
	return staged;
};

const collect = async () => {
	const staged = await gather();

	if (!staged) {
		if (existsSync(STAGING_FILE)) await rm(STAGING_FILE);
		console.log("No What's New entries in the pending changesets.");
		return;
	}

	await writeFile(STAGING_FILE, `${JSON.stringify(staged, null, 2)}\n`);
	console.log(
		`Staged ${staged.entries.length} What's New ${staged.entries.length === 1 ? "entry" : "entries"}.`,
	);
};

const readNotes = async (): Promise<Array<ReleaseNote>> => {
	if (!existsSync(DATA_FILE)) return [];
	const module = await import(DATA_FILE.href);
	return module.RELEASE_NOTES ?? [];
};

const withoutPreview = (notes: Array<ReleaseNote>): Array<ReleaseNote> =>
	notes.filter((note) => note.version !== PREVIEW_VERSION);

const quote = (value: string) => JSON.stringify(value);

const identifierFor = (icon: string) =>
	`${icon
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean)
		.map((part) => part[0].toUpperCase() + part.slice(1))
		.join("")}Icon`;

const writeDataFile = async (notes: Array<ReleaseNote>) => {
	const lines = [
		GENERATED_HEADER,
		"",
		'import type { ReleaseNote, ReleaseNoteEntry } from "@colibri-social/lib";',
		'import type { ReleaseNoteIcon } from "./icons";',
		"",
		"export type ClientReleaseNote = Omit<ReleaseNote, \"entries\"> & {",
		"\tentries: Array<Omit<ReleaseNoteEntry, \"icon\"> & { icon: ReleaseNoteIcon }>;",
		"};",
		"",
		"export const RELEASE_NOTES: Array<ClientReleaseNote> = [",
	];

	for (const note of notes) {
		lines.push("\t{");
		lines.push(`\t\tversion: ${quote(note.version)},`);
		lines.push(`\t\tdate: ${quote(note.date)},`);
		if (note.title) lines.push(`\t\ttitle: ${quote(note.title)},`);
		if (note.heroImage) lines.push(`\t\theroImage: ${quote(note.heroImage)},`);
		lines.push("\t\tentries: [");
		for (const entry of note.entries) {
			lines.push("\t\t\t{");
			lines.push(`\t\t\t\ttitle: ${quote(entry.title)},`);
			lines.push(`\t\t\t\tbody: ${quote(entry.body)},`);
			lines.push(`\t\t\t\ticon: ${quote(entry.icon)},`);
			lines.push(`\t\t\t\tkind: ${quote(entry.kind)},`);
			lines.push("\t\t\t},");
		}
		lines.push("\t\t],");
		lines.push("\t},");
	}

	lines.push("];", "");

	await writeGenerated(DATA_FILE, lines.join("\n"));
};

const writeIconsFile = async (notes: Array<ReleaseNote>) => {
	const icons = [
		...new Set([
			FALLBACK_ICON,
			...notes.flatMap((note) => note.entries.map((entry) => entry.icon)),
		]),
	].sort();

	const lines = [GENERATED_HEADER, ""];
	for (const icon of icons) {
		lines.push(`import ${identifierFor(icon)} from "~icons/ph/${icon}";`);
	}
	if (icons.length > 0) lines.push("");

	lines.push("export const RELEASE_NOTE_ICONS = {");
	for (const icon of icons) {
		lines.push(`\t${quote(icon)}: ${identifierFor(icon)},`);
	}
	lines.push("} as const;", "");
	lines.push(
		"export type ReleaseNoteIcon = keyof typeof RELEASE_NOTE_ICONS;",
		"",
		`export const FALLBACK_RELEASE_NOTE_ICON = ${quote(FALLBACK_ICON)} satisfies ReleaseNoteIcon;`,
		"",
	);

	await writeGenerated(ICONS_FILE, lines.join("\n"));
};

const format = () => {
	const paths = [DATA_FILE, ICONS_FILE].map((url) => fileURLToPath(url));
	spawnSync("pnpm", ["biome", "check", "--write", ...paths], {
		stdio: "ignore",
	});
};

const finalize = async () => {
	if (!existsSync(STAGING_FILE)) {
		console.log("Nothing staged, leaving the release notes untouched.");
		return;
	}

	const staged = JSON.parse(await readFile(STAGING_FILE, "utf8")) as Staged;
	const { version } = JSON.parse(
		await readFile(CLIENT_PACKAGE_JSON, "utf8"),
	) as { version: string };

	const existing = withoutPreview(await readNotes());
	if (existing.some((note) => note.version === version)) {
		return fail(
			`release notes already contain version ${version}, refusing to add a second entry`,
		);
	}

	const note: ReleaseNote = {
		version,
		date: new Date().toISOString().slice(0, 10),
		entries: staged.entries,
	};
	if (staged.releaseTitle) note.title = staged.releaseTitle;
	if (staged.heroImage) note.heroImage = staged.heroImage;

	const notes = [note, ...existing].slice(0, KEEP_RELEASES);

	await writeDataFile(notes);
	await writeIconsFile(notes);
	format();
	await rm(STAGING_FILE);

	const pruned = existing.length + 1 - notes.length;
	console.log(
		`Added What's New notes for ${version}${pruned > 0 ? `, pruned ${pruned} older ${pruned === 1 ? "release" : "releases"}` : ""}.`,
	);
};

const generate = async () => {
	const all = await readNotes();
	const notes = withoutPreview(all);
	const dropped = all.length - notes.length;

	await writeDataFile(notes);
	await writeIconsFile(notes);
	format();

	console.log(
		`Regenerated release notes for ${notes.length} ${notes.length === 1 ? "release" : "releases"}${dropped > 0 ? ", removed the preview entry" : ""}.`,
	);
};

const preview = async () => {
	const staged = await gather();
	if (!staged) {
		return fail(
			"no What's New entries in the pending changesets, add one with `pnpm changeset:feature`",
		);
	}

	const note: ReleaseNote = {
		version: PREVIEW_VERSION,
		date: new Date().toISOString().slice(0, 10),
		entries: staged.entries,
	};
	if (staged.releaseTitle) note.title = staged.releaseTitle;
	if (staged.heroImage) note.heroImage = staged.heroImage;

	const notes = [note, ...withoutPreview(await readNotes())].slice(
		0,
		KEEP_RELEASES,
	);

	await writeDataFile(notes);
	await writeIconsFile(notes);
	format();

	console.log(
		`Wrote a preview release with ${staged.entries.length} ${staged.entries.length === 1 ? "entry" : "entries"}.`,
	);
	console.log(
		"Start the client to see it, then run `pnpm whats-new:generate` to remove it before committing.",
	);
};

const mode = process.argv[2];

if (mode === "collect") await collect();
else if (mode === "finalize") await finalize();
else if (mode === "generate") await generate();
else if (mode === "preview") await preview();
else
	fail(
		`unknown mode ${quote(mode ?? "")}, expected collect|finalize|generate|preview`,
	);
