// Generated by scripts/generate-error-codes.ts. Do not edit by hand.
// Run `pnpm error-codes:generate` after changing a lexicon's `errors`.

/** Every error code the AppView's lexicons declare. */
export type AppViewErrorCode =
	| "AuthRequired"
	| "CommunityCredentialsUnrecoverable"
	| "Forbidden"
	| "InvalidRequest"
	| "InvalidState"
	| "NotAnImage"
	| "NotEnabled"
	| "NotFound"
	| "PdsUnavailable"
	| "RateLimited"
	| "SfuError"
	| "TooManySubscribers"
	| "UpstreamFailure";

/** The lexicon's own description of each code, for diagnostics and dev output. */
export const APPVIEW_CODE_DESCRIPTIONS: Record<AppViewErrorCode, string> = {
	AuthRequired: "Missing, malformed, or unverifiable service auth.",
	CommunityCredentialsUnrecoverable:
		"The AppView cannot write to the community's repo and could not repair its own access.",
	Forbidden: "The caller lacks the permission this method requires.",
	InvalidRequest: "A parameter or body field was missing or malformed.",
	InvalidState: "The given state is not one of the accepted values.",
	NotAnImage: "The linked resource is not an image type the AppView serves.",
	NotEnabled: "Humming is disabled on this AppView.",
	NotFound: "The referenced record does not exist.",
	PdsUnavailable:
		"The PDS this operation needs is unreachable or is not a PDS.",
	RateLimited: "The caller exceeded its rate budget.",
	SfuError: "The SFU could not create the channel router or a transport.",
	TooManySubscribers: "The hub is at its subscribeHums connection limit.",
	UpstreamFailure: "A service outside this AppView failed.",
};

/** Which codes each method declares, keyed by NSID. */
export const APPVIEW_METHOD_ERRORS: Record<
	string,
	ReadonlyArray<AppViewErrorCode>
> = {
	"social.colibri.actor.getNotificationPreference": ["AuthRequired"],
	"social.colibri.actor.listCommunities": ["AuthRequired"],
	"social.colibri.actor.listMutes": ["AuthRequired"],
	"social.colibri.actor.setState": ["AuthRequired", "InvalidState"],
	"social.colibri.category.create": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.category.delete": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.category.update": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.channel.create": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.channel.delete": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.channel.getChannelView": ["AuthRequired", "InvalidRequest"],
	"social.colibri.channel.getReadCursor": [
		"AuthRequired",
		"InvalidRequest",
		"NotFound",
	],
	"social.colibri.channel.listMessages": ["InvalidRequest"],
	"social.colibri.channel.listReactions": ["InvalidRequest"],
	"social.colibri.channel.listUnreadStatus": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.channel.update": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.community.approveMembership": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.banUser": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.blockMessage": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.create": [
		"AuthRequired",
		"InvalidRequest",
		"PdsUnavailable",
		"UpstreamFailure",
	],
	"social.colibri.community.createInvitation": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotFound",
	],
	"social.colibri.community.delete": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotFound",
		"UpstreamFailure",
	],
	"social.colibri.community.deleteInvitation": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotFound",
	],
	"social.colibri.community.dismissApplication": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.getData": ["InvalidRequest", "NotFound"],
	"social.colibri.community.getInvitation": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotFound",
	],
	"social.colibri.community.kick": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.kickUser": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.leave": ["AuthRequired"],
	"social.colibri.community.listApplications": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.listBannedUsers": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.listCategories": ["InvalidRequest"],
	"social.colibri.community.listChannels": ["InvalidRequest"],
	"social.colibri.community.listInvitations": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotFound",
	],
	"social.colibri.community.listMembers": ["InvalidRequest"],
	"social.colibri.community.listRoles": ["InvalidRequest"],
	"social.colibri.community.migrate": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotFound",
		"UpstreamFailure",
	],
	"social.colibri.community.registerCredentials": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"InvalidRequest",
		"PdsUnavailable",
		"UpstreamFailure",
	],
	"social.colibri.community.reorderCategories": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.community.reorderChannels": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.community.setMemberRoles": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.community.unbanUser": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.undismissApplication": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.community.update": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.embed.getImage": ["NotAnImage", "RateLimited"],
	"social.colibri.embed.getMetadata": ["AuthRequired", "InvalidRequest"],
	"social.colibri.embed.gifCategories": ["AuthRequired"],
	"social.colibri.embed.searchGifs": ["AuthRequired", "InvalidRequest"],
	"social.colibri.embed.trendingGifs": ["AuthRequired"],
	"social.colibri.notification.getUnreadCount": ["AuthRequired"],
	"social.colibri.notification.getUnseen": ["AuthRequired"],
	"social.colibri.notification.listNotifications": ["AuthRequired"],
	"social.colibri.notification.registerPush": [
		"AuthRequired",
		"InvalidRequest",
	],
	"social.colibri.notification.unregisterPush": ["AuthRequired"],
	"social.colibri.notification.updateSeen": ["AuthRequired"],
	"social.colibri.notification.updateSeenForMessage": ["AuthRequired"],
	"social.colibri.role.create": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.role.delete": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.role.update": [
		"AuthRequired",
		"CommunityCredentialsUnrecoverable",
		"Forbidden",
		"InvalidRequest",
		"PdsUnavailable",
	],
	"social.colibri.sync.sendHum": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
		"NotEnabled",
		"RateLimited",
	],
	"social.colibri.sync.subscribeEvents": ["AuthRequired"],
	"social.colibri.sync.subscribeHums": [
		"AuthRequired",
		"NotEnabled",
		"TooManySubscribers",
	],
	"social.colibri.voice.moderate": [
		"AuthRequired",
		"Forbidden",
		"InvalidRequest",
	],
	"social.colibri.voice.signal": ["AuthRequired", "Forbidden", "SfuError"],
};

export const isAppViewErrorCode = (value: string): value is AppViewErrorCode =>
	value in APPVIEW_CODE_DESCRIPTIONS;
